"""new offer properties

Revision ID: 37caec309f06
Revises: b9b9d910b10b
Create Date: 2021-02-21 15:09:35.014723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37caec309f06'
down_revision = 'b9b9d910b10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('condition', sa.String(length=64), nullable=True))
    op.add_column('offer', sa.Column('expiration', sa.DateTime(), nullable=True))
    op.add_column('offer', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('offer', sa.Column('request', sa.Boolean(), nullable=True))
    op.add_column('offer', sa.Column('servings', sa.Integer(), nullable=True))
    op.add_column('offer', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'title')
    op.drop_column('offer', 'servings')
    op.drop_column('offer', 'request')
    op.drop_column('offer', 'price')
    op.drop_column('offer', 'expiration')
    op.drop_column('offer', 'condition')
    op.drop_column('offer', 'category_id')
    # ### end Alembic commands ###
