"""new user properties

Revision ID: b9b9d910b10b
Revises: b92f21810253
Create Date: 2021-02-21 15:05:41.149357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b9d910b10b'
down_revision = 'b92f21810253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('interest', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('postal_code', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('state_province', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'state_province')
    op.drop_column('user', 'postal_code')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'interest')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'country')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
