"""lat long

Revision ID: c3237035fb7e
Revises: 08817912ac76
Create Date: 2021-03-06 17:17:27.769627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3237035fb7e'
down_revision = '08817912ac76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lng')
    op.drop_column('user', 'lat')
    # ### end Alembic commands ###
